site_name: Educational Set AI
site_url: https://sickag.github.io/Edu-AI
use_directory_urls: false
nav:
  - Home: index.md
  - Overview: 
    - Foreword: overview/foreword.md
    - What's in the box: overview/box.md
    - Accounts: overview/accounts.md
  - Exercises: 
    - Exercise 1: exercises/exercise1.md
    - Exercise 2: exercises/exercise2.md
    - Exercise 3: exercises/exercise3.md
  - Troubleshoot: troubleshoot.md
  - FAQ: faq.md
  - Imprint: https://www.sick.com/de/de/s/imprint

theme:
  language: en
  name: material
  palette:
    primary: custom
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/sick_logo.png'
  features:
    - content.code.copy
  favicon: 'images/favicon.ico'
extra_css:
  - stylesheets/extra.css
copyright: "Â© SICK AG 2025"
plugins:
  - mkdocs-video

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true